print(1011+20)
print("5"+"6")
print(int("5")+int("6"))
print("This costs " + str(9) + " Dollars")
print("This costs " + str(9+12) + " Dollars")
print("Hello:All")
print(5==5)
print(5==3)
print(5 is 5)
print(5 is not 5)
print(5 is not 6)